console.log("hello from Js Variables");
let age = 15;
console.log(age);
age = 40;
console.log(age);
const myName = "Bat";
console.log(myName);
const mySonName = "Elbeg";
console.log(mySonName);
console.log("true or false");
const isMarried = false;
console.log(age);
let number = 32;
const mybrothername = "Bayraa";
console.log(mybrothername);
